### ISSUE TITLE
USER STORY: Submit a Poll Response

### ISSUE THREAD

**Issue by sophiejacques123** [sophiebatten123/love-running#1]
**User Story 1:**

In order to **provide anonymous feedback** as a **user**, I can **hide my identity in the poll response**

### Acceptance Criteria

- The option should be provided as a checkbox

- The checkbox should be “checked” by default

- The option should appear next to the submit button

- After submitting the default submission confirmation should be adjusted to include the user name.

### Tasks

- [ ] Design a checkbox icon and add this onto the user feedback poll . Create the HTML and CSS for the checkbox icon and ensure it is always by default selected.
- [ ] Create a field in the model to track the username.
- [ ] Update the controller function.
- [ ] Update the test script.
- [ ] Test the functionality.
